const CONSTANCE = {
    OS_ONLOAD: "OS_ONLOAD",
    OS_ONREADY: "OS_ONREADY",
    OS_SHUTDOWN: "OS_SHUTDOWN",
    OS_WINDOW_LIST_OPEN: "OS_WINDOW_LIST_OPEN",
    OS_WINDOW_NEXT: "OS_WINDOW_NEXT",
    OS_WINDOW_PREV: "OS_WINDOW_PREV",
}
export default CONSTANCE